import { Timestamp } from "firebase/firestore";
import { Property, Tenant, Invoice, DashboardStats, Expense } from "@/types";

// Helper to create timestamps for demo data
const createTimestamp = (daysAgo: number = 0): Timestamp => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return Timestamp.fromDate(date);
};

const createFutureTimestamp = (daysAhead: number): Timestamp => {
  const date = new Date();
  date.setDate(date.getDate() + daysAhead);
  return Timestamp.fromDate(date);
};

// Demo Properties
export const demoProperties: Property[] = [
  {
    id: "demo-prop-1",
    ownerId: "demo-user",
    name: "গুলশান অ্যাপার্টমেন্ট",
    address: "রোড ১১, গুলশান-২, ঢাকা-১২১২",
    totalUnits: 6,
    propertyType: "apartment",
    createdAt: createTimestamp(180),
    updatedAt: createTimestamp(30),
  },
  {
    id: "demo-prop-2",
    ownerId: "demo-user",
    name: "বনানী বাড়ি",
    address: "বনানী, ব্লক-এফ, ঢাকা-১২১৩",
    totalUnits: 4,
    propertyType: "house",
    createdAt: createTimestamp(120),
    updatedAt: createTimestamp(15),
  },
  {
    id: "demo-prop-3",
    ownerId: "demo-user",
    name: "ধানমন্ডি ফ্ল্যাট",
    address: "ধানমন্ডি ২৭, ঢাকা-১২০৫",
    totalUnits: 8,
    propertyType: "apartment",
    createdAt: createTimestamp(90),
    updatedAt: createTimestamp(5),
  },
];

// Demo Tenants
export const demoTenants: Tenant[] = [
  {
    id: "demo-tenant-1",
    propertyId: "demo-prop-1",
    ownerId: "demo-user",
    unitNumber: "A-101",
    name: "রহিম উদ্দিন",
    email: "rahim@example.com",
    phone: "+880 1712-345678",
    nid: "1234567890123",
    nidFrontUrl: "",
    nidBackUrl: "",
    photoUrl: "",
    agreementDocUrl: "",
    monthlyRent: 25000,
    gasCharge: 1500,
    waterCharge: 500,
    serviceCharge: 2000,
    currentBill: 0,
    advanceAmount: 50000,
    advanceMonths: 2,
    moveInDate: createTimestamp(365),
    status: "active",
    createdAt: createTimestamp(365),
    updatedAt: createTimestamp(30),
  },
  {
    id: "demo-tenant-2",
    propertyId: "demo-prop-1",
    ownerId: "demo-user",
    unitNumber: "A-102",
    name: "করিম হোসেন",
    email: "karim@example.com",
    phone: "+880 1812-456789",
    nid: "2345678901234",
    nidFrontUrl: "",
    nidBackUrl: "",
    photoUrl: "",
    agreementDocUrl: "",
    monthlyRent: 22000,
    gasCharge: 1500,
    waterCharge: 500,
    serviceCharge: 2000,
    currentBill: 26000,
    advanceAmount: 44000,
    advanceMonths: 2,
    moveInDate: createTimestamp(300),
    status: "active",
    createdAt: createTimestamp(300),
    updatedAt: createTimestamp(15),
  },
  {
    id: "demo-tenant-3",
    propertyId: "demo-prop-2",
    ownerId: "demo-user",
    unitNumber: "B-1",
    name: "সালমা আক্তার",
    email: "salma@example.com",
    phone: "+880 1912-567890",
    nid: "3456789012345",
    nidFrontUrl: "",
    nidBackUrl: "",
    photoUrl: "",
    agreementDocUrl: "",
    monthlyRent: 35000,
    gasCharge: 2000,
    waterCharge: 800,
    serviceCharge: 3000,
    currentBill: 0,
    advanceAmount: 70000,
    advanceMonths: 2,
    moveInDate: createTimestamp(200),
    status: "active",
    createdAt: createTimestamp(200),
    updatedAt: createTimestamp(10),
  },
  {
    id: "demo-tenant-4",
    propertyId: "demo-prop-3",
    ownerId: "demo-user",
    unitNumber: "C-201",
    name: "জাহিদ হাসান",
    email: "zahid@example.com",
    phone: "+880 1612-678901",
    nid: "4567890123456",
    nidFrontUrl: "",
    nidBackUrl: "",
    photoUrl: "",
    agreementDocUrl: "",
    monthlyRent: 18000,
    gasCharge: 1200,
    waterCharge: 400,
    serviceCharge: 1500,
    currentBill: 21100,
    advanceAmount: 36000,
    advanceMonths: 2,
    moveInDate: createTimestamp(150),
    status: "active",
    createdAt: createTimestamp(150),
    updatedAt: createTimestamp(5),
  },
  {
    id: "demo-tenant-5",
    propertyId: "demo-prop-3",
    ownerId: "demo-user",
    unitNumber: "C-202",
    name: "নাসরিন বেগম",
    email: "nasrin@example.com",
    phone: "+880 1512-789012",
    nid: "5678901234567",
    nidFrontUrl: "",
    nidBackUrl: "",
    photoUrl: "",
    agreementDocUrl: "",
    monthlyRent: 20000,
    gasCharge: 1200,
    waterCharge: 400,
    serviceCharge: 1500,
    currentBill: 0,
    advanceAmount: 40000,
    advanceMonths: 2,
    moveInDate: createTimestamp(100),
    status: "active",
    createdAt: createTimestamp(100),
    updatedAt: createTimestamp(2),
  },
];

// Demo Invoices
export const demoInvoices: Invoice[] = [
  {
    id: "demo-inv-1",
    tenantId: "demo-tenant-1",
    propertyId: "demo-prop-1",
    ownerId: "demo-user",
    tenantName: "রহিম উদ্দিন",
    tenantEmail: "rahim@example.com",
    unitNumber: "A-101",
    month: "এপ্রিল ২০২৬",
    rent: 25000,
    gasCharge: 1500,
    waterCharge: 500,
    serviceCharge: 2000,
    electricityBill: 1500,
    totalAmount: 30500,
    paidAmount: 30500,
    dueAmount: 0,
    dueDate: createTimestamp(5),
    status: "paid",
    paymentDate: createTimestamp(3),
    paymentMethod: "bKash",
    receiptUrl: null,
    emailSent: true,
    emailSentAt: createTimestamp(3),
    createdAt: createTimestamp(30),
    updatedAt: createTimestamp(3),
  },
  {
    id: "demo-inv-2",
    tenantId: "demo-tenant-2",
    propertyId: "demo-prop-1",
    ownerId: "demo-user",
    tenantName: "করিম হোসেন",
    tenantEmail: "karim@example.com",
    unitNumber: "A-102",
    month: "এপ্রিল ২০২৬",
    rent: 22000,
    gasCharge: 1500,
    waterCharge: 500,
    serviceCharge: 2000,
    electricityBill: 1200,
    totalAmount: 27200,
    paidAmount: 0,
    dueAmount: 27200,
    dueDate: createTimestamp(-5),
    status: "overdue",
    paymentDate: null,
    paymentMethod: null,
    receiptUrl: null,
    emailSent: true,
    emailSentAt: createTimestamp(10),
    createdAt: createTimestamp(30),
    updatedAt: createTimestamp(1),
  },
  {
    id: "demo-inv-3",
    tenantId: "demo-tenant-3",
    propertyId: "demo-prop-2",
    ownerId: "demo-user",
    tenantName: "সালমা আক্তার",
    tenantEmail: "salma@example.com",
    unitNumber: "B-1",
    month: "এপ্রিল ২০২৬",
    rent: 35000,
    gasCharge: 2000,
    waterCharge: 800,
    serviceCharge: 3000,
    electricityBill: 2200,
    totalAmount: 43000,
    paidAmount: 43000,
    dueAmount: 0,
    dueDate: createFutureTimestamp(5),
    status: "paid",
    paymentDate: createTimestamp(1),
    paymentMethod: "Nagad",
    receiptUrl: null,
    emailSent: true,
    emailSentAt: createTimestamp(1),
    createdAt: createTimestamp(25),
    updatedAt: createTimestamp(1),
  },
  {
    id: "demo-inv-4",
    tenantId: "demo-tenant-4",
    propertyId: "demo-prop-3",
    ownerId: "demo-user",
    tenantName: "জাহিদ হাসান",
    tenantEmail: "zahid@example.com",
    unitNumber: "C-201",
    month: "এপ্রিল ২০২৬",
    rent: 18000,
    gasCharge: 1200,
    waterCharge: 400,
    serviceCharge: 1500,
    electricityBill: 1000,
    totalAmount: 22100,
    paidAmount: 10000,
    dueAmount: 12100,
    dueDate: createFutureTimestamp(10),
    status: "partial",
    paymentDate: createTimestamp(2),
    paymentMethod: "Bank Transfer",
    receiptUrl: null,
    emailSent: true,
    emailSentAt: createTimestamp(2),
    createdAt: createTimestamp(20),
    updatedAt: createTimestamp(2),
  },
  {
    id: "demo-inv-5",
    tenantId: "demo-tenant-5",
    propertyId: "demo-prop-3",
    ownerId: "demo-user",
    tenantName: "নাসরিন বেগম",
    tenantEmail: "nasrin@example.com",
    unitNumber: "C-202",
    month: "এপ্রিল ২০২৬",
    rent: 20000,
    gasCharge: 1200,
    waterCharge: 400,
    serviceCharge: 1500,
    electricityBill: 1100,
    totalAmount: 24200,
    paidAmount: 24200,
    dueAmount: 0,
    dueDate: createFutureTimestamp(15),
    status: "paid",
    paymentDate: createTimestamp(0),
    paymentMethod: "Cash",
    receiptUrl: null,
    emailSent: false,
    emailSentAt: null,
    createdAt: createTimestamp(15),
    updatedAt: createTimestamp(0),
  },
];

// Demo Expenses
export const demoExpenses: Expense[] = [
  {
    id: "demo-exp-1",
    ownerId: "demo-user",
    propertyId: "demo-prop-1",
    propertyName: "গুলশান অ্যাপার্টমেন্ট",
    unitNumber: "",
    category: "maintenance",
    description: "লিফট মেরামত",
    amount: 15000,
    date: createTimestamp(10),
    createdAt: createTimestamp(10),
    updatedAt: createTimestamp(10),
  },
  {
    id: "demo-exp-2",
    ownerId: "demo-user",
    propertyId: "demo-prop-1",
    propertyName: "গুলশান অ্যাপার্টমেন্ট",
    unitNumber: "",
    category: "service",
    description: "মাসিক সার্ভিস চার্জ (কমন এরিয়া)",
    amount: 8000,
    date: createTimestamp(5),
    createdAt: createTimestamp(5),
    updatedAt: createTimestamp(5),
  },
  {
    id: "demo-exp-3",
    ownerId: "demo-user",
    propertyId: "demo-prop-2",
    propertyName: "বনানী বাড়ি",
    unitNumber: "",
    category: "utility",
    description: "বিদ্যুৎ বিল (কমন)",
    amount: 5000,
    date: createTimestamp(7),
    createdAt: createTimestamp(7),
    updatedAt: createTimestamp(7),
  },
  {
    id: "demo-exp-4",
    ownerId: "demo-user",
    propertyId: "demo-prop-3",
    propertyName: "ধানমন্ডি ফ্ল্যাট",
    unitNumber: "C-201",
    category: "maintenance",
    description: "প্লাম্বিং মেরামত",
    amount: 3500,
    date: createTimestamp(15),
    createdAt: createTimestamp(15),
    updatedAt: createTimestamp(15),
  },
  {
    id: "demo-exp-5",
    ownerId: "demo-user",
    propertyId: "demo-prop-1",
    propertyName: "গুলশান অ্যাপার্টমেন্ট",
    unitNumber: "",
    category: "tax",
    description: "সিটি কর্পোরেশন ট্যাক্স",
    amount: 25000,
    date: createTimestamp(45),
    createdAt: createTimestamp(45),
    updatedAt: createTimestamp(45),
  },
];

// Demo Dashboard Stats
export const demoDashboardStats: DashboardStats = {
  totalProperties: demoProperties.length,
  totalTenants: demoTenants.length,
  totalRevenue: demoInvoices
    .filter((inv) => inv.status === "paid")
    .reduce((sum, inv) => sum + inv.paidAmount, 0),
  pendingPayments: demoInvoices
    .filter((inv) => inv.status === "unpaid" || inv.status === "partial")
    .reduce((sum, inv) => sum + inv.dueAmount, 0),
  openTickets: 2,
  overdueInvoices: demoInvoices.filter((inv) => inv.status === "overdue").length,
};

// Get tenant by ID
export const getDemoTenant = (id: string): Tenant | undefined => {
  return demoTenants.find((t) => t.id === id);
};

// Get property by ID
export const getDemoProperty = (id: string): Property | undefined => {
  return demoProperties.find((p) => p.id === id);
};

// Get invoices for a tenant
export const getDemoInvoicesForTenant = (tenantId: string): Invoice[] => {
  return demoInvoices.filter((inv) => inv.tenantId === tenantId);
};

// Get tenants for a property
export const getDemoTenantsForProperty = (propertyId: string): Tenant[] => {
  return demoTenants.filter((t) => t.propertyId === propertyId);
};

// Get expenses for a property
export const getDemoExpensesForProperty = (propertyId: string): Expense[] => {
  return demoExpenses.filter((e) => e.propertyId === propertyId);
};
